# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2020
customText = "ä¸‹åŒ—æ³½ICPå¤‡ çº¢èŒ¶114514å·"

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ğŸ"
subtitle = "ç„¶åã€‚æˆ‘ã€å°†è¿™ä¸ªæ··è´¦çš„ç«™ç‚¹å‘å¸ƒäº†"

[sidebar.avatar]
enabled = true
local = true
src = "/MCSeekeri.jpg"

[article]
math = false
readingTime = true

[article.license]
enabled = true
default = "æœ¬ç«™æ‰€æœ‰å†…å®¹éƒ½ç»è¿‡äº†åŸä½œè€…çš„æˆæƒ"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 15

[[widgets.page]]
type = "toc"

[defaultImage.opengraph]
enabled = true
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "waline"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = "https://comments.sciadv.mcseekeri.top"
lang = ""
visitor = ""
avatar = ""
requiredMeta = ["name", "email", "url"]
placeholder = ""
pageview = true
comment = true
recaptchaV3Key = "6Lf9KTAbAAAAALfqwFyJmbRTABDc3MwyCKo696gp"
emoji = ["https://cdn.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/QQ", "https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/Tieba", "https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/Tieba-New", "https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/weibo", "https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/Coolapk", "https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/Heybox", "https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/bilibili2233/", "https://jsd.onmicrosoft.cn/gh/GamerNoTitle/ValineCDN@master/Menhera-chan"]
reaction = ["https://unpkg.com/@waline/emojis@1.1.0/tieba/tieba_agree.png", "https://unpkg.com/@waline/emojis@1.1.0/tieba/tieba_doubt.png", "https://unpkg.com/@waline/emojis@1.1.0/tieba/tieba_heart.png", "https://unpkg.com/@waline/emojis@1.1.0/tieba/tieba_lovely.png", "https://unpkg.com/@waline/emojis@1.1.0/tieba/tieba_rage.png", "https://unpkg.com/@waline/emojis@1.1.0/tieba/tieba_cry.png", "https://unpkg.com/@waline/emojis@1.1.0/tieba/tieba_awkward.png", "https://unpkg.com/@waline/emojis@1.1.0/tieba/tieba_vomit.png"]



[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
